### PR TITLE
Replace majority of user-facing, hard-coded strings with settings

### LINKED ISSUE #384: Replace hard-coded deployment-specific strings with variables
After #380, a single branch will be used for managing both BRC and LRC deployments.

Many deployment-specific strings (e.g., "MyBRC", "BRC", "Berkeley", "Savio", etc.) are hard-coded into user-facing text. Replace these with variables (in Django and by extension Ansible) as much as possible.

### PR DESCRIPTION
**Pull request by matthew-li**
Fixes #384

**Changes**
- Introduced three new settings:
	- `PORTAL_NAME`: "MyBRC" or "MyLRC"
	- `PROGRAM_NAME_LONG`: "Berkeley Research Computing" or "Laboratory Research Computing"
	- `PROGRAM_NAME_SHORT`: "BRC" or "LRC"
- Introduced corresponding Ansible variables for configuring them in `main.yml`.
- Replaced hard-coded strings with the new settings.
- Added a context processor `portal_and_program_names` so that the new settings are available in templates without being explicitly set as context variables.
- Refactored LRC-/BRC-specific documentation text in emails sent when a user joins/is added to a project into separate templates.
- Refactored the feedback alert into a template.
- Corrected `full_host_path` in the development `main.copyme` to fix the nav-bar "Help" link.

**How to Test**
- Review the code changes and add comments as needed.
	- Search for various terms like "Berkeley", "BRC", "MyBRC", "CalNet", "Savio", etc. Note any instances not covered by the exceptions below.
- Ensure that the test suite passes.
- Manual Testing
	- On both an LRC-based VM and a BRC-based VM, checkout the branch, configure new Ansible variables, re-run the playbook, and look for inconsistencies or errors around the UI.

**Notes**
- Not all deployment-specific words have been replaced. Notable exceptions include:
	- The user access agreement
	- The survey for new project requests
	- Savio/Vector new project requests (including URL paths)
	- `ACCOUNT_CREATION_TEXT` and some login/registration/password-reset help text
		- These can be ignored because they should not appear based on flags introduced in `issue_276`.
	- Feedback alert
	- The "Savio Compute" `Resource`

### CODE REVIEW

**Comment by matthew-li** [comment]
Tests are passing on my machine after #417 is merged.

**Comment by jofeinstein** [comment]
help.html still has a lot of BRC references. Also, are we going to update all of the email addresses in the portal, ie research-it@berkeley.edu, brc@berkeley.edu, ...

**Comment by jofeinstein** [comment]
Test suite passes on my BRC vm. 

On my LRC vm, `get_current_allowance_year_period` cannot find a matching AllocationPeriod since the one allocation period created in `create_allocation_periods` has not started yet. I added another AllocationPeriod to be created in `create_allocation_periods.py` to fix this.

Also, in `coldfront.core.project.tests.test_utils.test_renewal_utils.test_allocation_renewal_approval_runner.TestUnpooledToUnpooled`, the allocation period start dates in the emails are printed with the month abbreviation instead of the entire month name like in the tests. For example, 10-1-2021 would be printed as Oct. 1, 2021 in my VM whereas the test expects October 1, 2021. I don't know if how Django renders the dates in the emails is machine specific.

**Comment by matthew-li** [comment]
@jofeinstein Thanks. I've replaced the one email with the setting, and I've made a note to address the rest of the text separately.

As for tests, had you merged #417 in? That PR addressed at least the first issue you raised. (It's merged into this branch now.)

For the date formatting issue, I think you're referring to `test_runner_sends_emails_conditionally`. The formatting is done using:

```
formatted_start_date = request.allocation_period.start_date.strftime('%B %-d, %Y')
```

On my box, I get:

```
(venv) [vagrant@vagrant coldfront]$ python
Python 3.6.8 (default, Nov 10 2020, 07:30:01) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import date
>>> d = date(2021, 10, 1)
>>> d.strftime('%B %-d, %Y')
'October 1, 2021'
```

Do you see 'Oct. 1, 2021' in the shell on your box?

**Pull request merged**
