### PR TITLE
Issue 232

### PR DESCRIPTION
**Pull request by jofeinstein**
- Jobs submitted that do not have start/end dates within the given allocations start/end dates will not be created or updated 
-  added logic to create and update functions in `coldfront/api/statistics/views.py`

- added tests to `coldfront/api/statistics/tests/test_job_view_set.py` for new functionality. 

- altered test base and other tests in `coldfront/api/statistics/tests/test_job_view_set.py` to reflect the fact that we now assume all allocations have start dates

### CODE REVIEW

**Review by matthew-li — CHANGES_REQUESTED** [review]
To clarify, we just want to avoid updating usages, not raise an error, as we still want to store a record of the job.

In general, we want to be as lenient as possible to avoid disrupting user jobs. (For example, when the API is down, all jobs go through automatically rather than failing.)

So if the job doesn't have a date (unlikely, but not impossible), or an allocation doesn't have an expected date (unlikely, but not impossible), or the job date is outside of the allocation range, etc., we should skip the block that performs the SU usage update, but still save the job.

**Comment by jofeinstein** [comment]
I thought we could assume that all allocations have start dates and then some have end dates depending on the type. Should we still add checks just to make sure?

**Comment by jofeinstein** [comment]
Okay. I'll add some checks so it doesn't fail

**Comment by jofeinstein** [comment]
I added a few new if statements to catch allocations that don't have start/end dates and added some tests for them

**Comment by jofeinstein** [comment]
I made the changes discussed in the meeting today

**Comment by matthew-li** [comment]
I'll make some changes to this once #400 is merged.

**Comment by matthew-li** [comment]
**Changes**
- Refactored date validation logic into a method.
- Added and updated tests for date validation logic.
- Resolved a bug wherein timezone-naive `datetimes` were being used to filter `Jobs` on `GET` requests.
- Resolved test warnings about comparing timezone-naive and timezone-aware `datetimes`.
- Removed a legacy method that assumed a particular start date for Allowance Years, given that these are now handled by `AllocationPeriods`.
- Created `AllocationPeriods` in API tests.
- (Unrelated) Fixed tests that fail specifically in the current month (May) because the `ALLOCATION_RENEWAL_FOR_NEXT_PERIOD_REQUESTABLE` flag is enabled by settings.

@jofeinstein Thanks for getting the ball rolling on this. Can you check that the validation logic still makes sense, and that the test suite passes for you? (The warnings should be gone now.)

**Comment by jofeinstein** [comment]
Test suite still passes for me

**Review by matthew-li — APPROVED** [review]

**Pull request merged**
