### PR TITLE
Generalize allowance-related handling for LRC; replace hard-coded strings; hide deployment-specific functionality

### LINKED ISSUE #384: Replace hard-coded deployment-specific strings with variables
After #380, a single branch will be used for managing both BRC and LRC deployments.

Many deployment-specific strings (e.g., "MyBRC", "BRC", "Berkeley", "Savio", etc.) are hard-coded into user-facing text. Replace these with variables (in Django and by extension Ansible) as much as possible.

### LINKED ISSUE #414: Support BRC and LRC allocation types
For BRC, there are five allocation types: `ac_`, `co_`, `fc_`, `ic_` and `pc_`, which are hard-coded in multiple places in the codebase.

For LRC, there are only three: `ac_`, `co_`, and `pc_`. The first two behave the same, but `pc_` is equivalent to `fc_` on BRC.

- [x] Refactor hard-coded allocation types into settings.
- [x] Adjust the new project request, approval, and processing flows to account for these different types.
- [x] Adjust the allocation renewal request, approval, and processing flows to account for these different types.

### PR DESCRIPTION
**Pull request by matthew-li**
Refs #383
Fixes #384
Fixes #414

**Changes**
- Added the concept of a computing allowance, modeled as a `Resource`. This replaces hard-coded `allocation_type` strings (e.g., `SavioProjectAllocationRequest.FCA`, etc.) with values stored in the database.
    - Each `Resource` has multiple `ResourceAttributeTypes` (see `add_allowance_defaults` for examples):
        - `code` (the three letter prefix before a project name)
        - `name_short` (a short name for the allowance)
        - `name_long` (a long name for the allowance)
        - `Service Units` (the default number of service units to assign to an `Allocation` to this allowance, if applicable)
    - Added a class `ComputingAllowanceInterface` for fetching attribute values or the associated `Resource` objects.
    - Added a class `ComputingAllowance` to wrap around computing allowance `Resources` and provide answers to deployment-specific questions.
        - E.g., does this allowance have infinite service units? Is it a periodic allowance? Is it yearly? Can it be pooled? Does it require an MOU?
            - Replaced checks against allocation types/prefixes with these methods.
    - Added a foreign key to the corresponding computing allowance `Resource` to new project requests and `AllocationRenewalRequests`.
    - Replaced `allocation_type` with `computing_allowance` in forms, views, tests, etc.
        - The field was left for now, but could be removed later.
        - Removed `ALLOCATION_TYPE_CHOICES` from `SavioProjectAllocationRequest`.
- Removed hard-coded references to project name prefixes (e.g., `fc_`) in *non-test* code.
- Removed hard-coded references to "Savio".
    - Renamed new project request views to be general.
    - Displayed the correct cluster name in various places.
- Limited the following functionality to BRC:
    - Service Unit Purchase Requests (Project Detail view for Recharge projects, Request Hub, Navbar)
    - New Vector project requests (Create a new project, Request Hub, Navbar)
    - Requirement of an MOU for new Recharge project requests
- Removed all references to the `AllocationAttributeType` named `{CLUSTER_NAME} Allocation Type`, which served no purpose.
- Introduced the following settings:
    - `PRIMARY_CLUSTER_NAME` ("Savio" for BRC, "Lawrencium" for LRC)
        - Replaced hard-coded references to "Savio" with the setting.
        - Added utility methods for deriving the correct "{CLUSTER_NAME} Compute" `Resource` from the setting, so that references to "Savio Compute" could be replaced.
- Removed the following settings:
    - `CO_DEFAULT_ALLOCATION` (now stored in database)
    - `ICA_DEFAULT_ALLOCATION` (now stored in database)
    - `FCA_DEFAULT_ALLOCATION` (now stored in database)
    - `PCA_DEFAULT_ALLOCATION` (now stored in database)
- Introduced the following feature flags:
    - `SERVICE_UNITS_PURCHASABLE` (`True` for BRC, `False` for LRC)
- Introduced the following management commands:
    - `add_allowance_defaults` (create new `Resources` and `ResourceAttributeTypes`)
    - `set_new_project_request_computing_allowances` (set computing allowances for existing new project requests)
    - `set_allocation_renewal_request_computing_allowances` (set computing allowances for existing `AllocationRenewalRequests`)

**How to Test**
- Ensure that the test suite passes on both a BRC-based VM and an LRC-based VM.
    - The Ansible playbook should be re-run first.
- Manual Testing
    - Set `primary_cluster_name` in `main.yml` to "Savio"/"Lawrencium".
    - Re-run the Ansible playbook.
    - Run the following management commands for setting new field values for existing objects:
        ```
        python manage.py set_new_project_request_computing_allowances # --dry_run first
        python manage.py set_allocation_renewal_request_computing_allowances # --dry_run first
        ```
    - Ensure that BRC-specific functionality is hidden from LRC.
    - Test miscellaneous request/approval flows and note any errors.
    - Note any missed references to deployment-specific strings.

**Notes**
- Tests remain highly BRC-specific.
- `SavioProjectAllocationRequest` has not been renamed.

### CODE REVIEW

**Comment by matthew-li** [comment]
@jofeinstein Can you see if the tests pass and if the website look reasonable on the LRC VM? (There are still some exceptions, like the feedback alert on the home page, the welcome text on the login page, the help page, the new project survey, the user agreement, etc. that have been/will be addressed elsewhere).

@Hzaakk Can you do the same on your BRC VM?

See the above instructions for more details.

These commands are really only relevant for BRC, since LRC doesn't really have any existing requests yet.
```
python manage.py set_new_project_request_computing_allowances # --dry_run first
python manage.py set_allocation_renewal_request_computing_allowances # --dry_run first
```

**Review by Hzaakk — COMMENTED** [review]
I ran the `./manage.py test` command and got no errors. I also made a Recharge and FCA project and purchased service units without issue. Seems to work for me.

**Comment by jofeinstein** [comment]
Secure directory join requests are still visible in the request hub

**Comment by jofeinstein** [comment]
I am getting `ComputingAllowanceInterfaceError` when I try to access `NANO, ETNA, VULCAN, MHG, and SCS` projects. It could be an issue with my local db. The error is thrown bc `ComputingAllowanceInterface._code_to_object` does not contain codes `'NAN' , 'ETN', etc...`

**Comment by matthew-li** [comment]
@jofeinstein

You addressed the visibility of those requests in `issue_132a`.

Thanks for catching these two bugs:
1. `ComputingAllowance` is only relevant for the primary cluster (Savio/Lawrencium), so I added a check to only attempt to fetch it if the Project corresponds to that cluster.
2. The variable-like string was appearing in `AllocationRenewalRequestUnderProjectView`, but not `AllocationRenewalRequestView`. I've copied over the prettifying-logic from the latter to the former.

Let me know if either of these still isn't resolved.

**Comment by matthew-li** [comment]
I've deployed this to BRC and LRC staging, and done some testing. Merging.

**Pull request merged**
