### PR TITLE
add bottom padding in login form

### PR DESCRIPTION
**Pull request by ViRu-ThE-ViRuS**
login page, add space beneath `Forgot Your Password?`

Screenshot from 2021-05-17 19-45-14

### CODE REVIEW

**Review by matthew-li — COMMENTED** [review]
This is what it looks like on a wider screen. In my opinion, the padding is too much. Also, the `<hr>` extends all the way to the edge, unlike the one above it.

after

**Comment by ViRu-ThE-ViRuS** [comment]
lemme try a <br> instead.. i couldnt see that line on my screen for some reason.

**Comment by matthew-li** [comment]
For reference, this is what it looks like for me on `develop`.

before

**Comment by matthew-li** [comment]
It looks fine on Safari and Chrome, but there's no padding on Firefox.

**Comment by ViRu-ThE-ViRuS** [comment]
> It looks fine on Safari and Chrome, but there's no padding on Firefox.

yeah, im on firefox and thats why this was looking weird. how do you propose we fix this?

**Comment by matthew-li** [comment]
Thanks for raising this. Can you confirm that this styling looks okay for you?

```
<div class="text-center" style="margin-bottom: 20px;">
  <a href="{% url 'password-reset' %}">Forgot your password?</a>
</div>
```

We should then create a new file `coldfront/static/core/user/css/login.css`, and move that styling into an `id` attribute.

**Comment by ViRu-ThE-ViRuS** [comment]
looks good! done @matthew-li

**Review by matthew-li — APPROVED** [review]
Thanks!

**Pull request merged**
