### PR TITLE
Fixed Database Dump File Loading Script

### PR DESCRIPTION
**Pull request by Hzaakk**
## Changes:
- DB loading script now drops and recreates DB before loading from dump file.
- Database is loaded without the "grep -v statistics_job" code which didn't work.
- Added an option to kill database connections before dropping DB. This prevents `ERROR:  database "cf_brc_db" is being accessed by other users`
- Also added an option for whether to exclude job data from loading. This is included in the first commit but removed in the second because the command to exclude job data doesn't work. If in the future, anyone finds a working way to exclude job data, then the code from the first commit can be used again with the new working way.
## How I tested Changes:
- First ran script with and without options. Then ran `./manage.py migrate`. Then made sure I could login to MyBRC and go to different pages.
## Usage Screenshots:
image
image

### CODE REVIEW

**Comment by jofeinstein** [comment]
This worked for me on a new VM. It's probably a good idea to update the main README section where we talk about loading in a database. The example command doesn't include the DB_NAME arg.

**Review by jofeinstein — COMMENTED** [review]
This worked for me on a new VM. It's probably a good idea to update the main README section where we talk about loading in a database. The example command doesn't include the DB_NAME arg.

**Comment by Hzaakk** [comment]
> This worked for me on a new VM. It's probably a good idea to update the main README section where we talk about loading in a database. The example command doesn't include the DB_NAME arg.

I've updated the README:
` # Load from the dump file.`
`sh bootstrap/development/load_database_backup.sh /absolute/path/to/dump.file`
becomes
`# Load from the dump file (use the -k option if the command errors because database is being accessed).`
`sh bootstrap/development/load_database_backup.sh [-k] DB_NAME /absolute/path/to/dump.file`

**Review by matthew-li — APPROVED** [review]
Thanks for addressing this. The code changes look reasonable--merging.

**Pull request merged**
